spring:
  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
    # show_sql: true
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

my:
  id: 100

mymy:
  idid: 200

config:
  leader:
    zookeeper:
      host: localhost:2181
      path: /test-leader/